#!/bin/bash

main() {
	mkdir -p "$PLUGIN_PATH/enabled" # until plugn ensures this for us
	if [[ "$INSTALL" ]]; then
		printf "%s\n" $INSTALL | xargs -L 1 plugn install
		printf "%s\n" $INSTALL | xargs -L 1 plugn trigger dependencies
	fi
	if [[ "$ENABLE" ]]; then
		printf "%s\n" $ENABLE | xargs -L 1 plugn enable
	fi
	echo "Starting docker-plugins with:"
	plugn list
	if [[ "$DEBUG" ]]; then
		dockerhook -d "/bin/plugn trigger"
	else
		dockerhook "/bin/plugn trigger"
	fi
}

main
